PalLocalPlanner:

  # main params
  acc_lim_x    : 0.6
  acc_lim_theta: !degrees 60.0
  xy_goal_tolerance : 0.2
  yaw_goal_tolerance: 0.2
  obstacle_avoider: 0 # VFH
  use_crowd       : false

  # mcc and oac params
  max_vel_x : &max_vel_x 0.3
  max_rot_vel: !degrees 30.0
  travel_speed_sfl   : *max_vel_x
  point_b_sfl        : 0.26
  decay              : 0.85
  max_dist_plan_ahead: 2.0
  dist_to_avoid      : 0.25
  allow_backwards    : false
  robotWidth      : 0.5

  transform_tolerance: 0.2
