controller_frequency: 10.0
controller_patience: 10.0
clearing_radius: 0.5
footprint_padding: 0.015
oscillation_timeout: 10.0
oscillation_distance: 0.2
base_local_planner: pal_local_planner/PalLocalPlanner
planner_frequency: 0.5
recovery_behavior_enabled: true
shutdown_costmaps: false
