PalLocalPlanner:
  transform_tolerance: 0.2

  max_vel_x: 1.0 
  max_vel_th: 0.7 
  
  acc_lim_th: 1.8 
  acc_lim_x: 0.45 

  xy_goal_tolerance: 0.15
  yaw_goal_tolerance: 0.20
  oscillation_reset_dist: 0.05

  travel_speed_sfl: 0.9
  point_b_sfl: 0.25
  decay: 0.85
  max_dist_plan_ahead: 20.0
  robot_module: 1.5
  dist_to_avoid: 0.7

