PalLocalPlanner:
  transform_tolerance: 0.2

  max_vel_x: 0.9 
  max_vel_th: 0.6 
  
  acc_lim_th: 2.4 
  acc_lim_x: 0.4 

  xy_goal_tolerance: 0.15
  yaw_goal_tolerance: 0.15
  oscillation_reset_dist: 0.1

  travel_speed_sfl: 0.9
  point_b_sfl: 0.26
  decay: 0.85
  max_dist_plan_ahead: 20.0
  robot_module: 1.5
  dist_to_avoid: 0.7

  robotWidth: 0.65
  robotLength: 0.75
  robotFrontLength: 0.18
  safetyDist: 2.2
