# Independent settings for the planner's costmap
global_costmap:
  # attention, the order and combination method matters
  plugins:
    - name: static_layer
      type: 'costmap_2d::StaticLayer'
    - name: obstacle_laser_layer
      type: 'costmap_2d::ObstacleLayer'
    - name: obstacle_sonar_layer
      type: 'costmap_2d::ObstacleLayer'
    - name: obstacle_vo_layer
      type: 'costmap_2d::ObstacleLayer'
    - name: obstacle_rgbd_layer
      type: 'costmap_2d::ObstacleLayer'
    - name: inflation_layer
      type: 'costmap_2d::InflationLayer'
