image_width: 640
image_height: 480
camera_name: base_rgbd_camera
camera_matrix:
  rows: 3
  cols: 3
  data: [534.912739751989, 0, 330.985394535914, 0, 533.854358032728, 228.556435595447, 0, 0, 1]
distortion_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [0.038068815642998, -0.0797226259386935, -7.70714015531115e-05, 0.00236125160500458, 0]
rectification_matrix:
  rows: 3
  cols: 3
  data: [1, 0, 0, 0, 1, 0, 0, 0, 1]
projection_matrix:
  rows: 3
  cols: 4
  data: [535.689758300781, 0, 331.978828845724, 0, 0, 535.773742675781, 228.025093169164, 0, 0, 0, 1, 0]
