scan_filter_chain:

- name: outlier
  type: pal_filters/LaserScanOutlierFilter
  params:
    distance_threshold: 0.5

- name: footprint_filter
  type: laser_filters/LaserScanFootprintFilter
  params:
    inscribed_radius: 0.30