port :                    /dev/ttyUSB0
frame_id:                 base_laser_link
ignore_array:             ''
baudrate:                 512000
lidar_type:               0
device_type:              0
sample_rate:              20
abnormal_check_count:     4

resolution_fixed:         true
auto_reconnect:           true
reversion:                true
inverted:                 true  
isSingleChannel:          false
intensity:                false
support_motor_dtr:        false
invalid_range_is_inf:     false
point_cloud_preservative: false

angle_min:                -65
angle_max:                 125
range_min:                0.01
range_max:                15.0
frequency:                10.0
